YUI.add('bpp-app-templates', function(Y){
// DO NOT EDIT THIS FILE
// this should be automatically generated by using the .*.html files in templates
Y.namespace('bpp.App');
Y.bpp.App.templates = {
    fader:Y.template('<div id="bpp-fader-container">\n	<div id="bpp-fader-overlay"></div>\n</div>')
};
}, '@VERSION@',{
    // [bug 5892107] no need to require assets     
    requires:['bpp-template']
});