YUI.add('bpp-gallery-templates', function(Y){
// DO NOT EDIT THIS FILE
// this should be automatically generated by using the .*.html files in templates
Y.namespace('bpp.Gallery');
Y.bpp.Gallery.templates = {
    base:Y.template('<div class="bpp-gallery pure-g-r">\n	<div class="loading"></div>\n</div>\n<div class="bpp-close icon-cog icon-large icon-remove-sign"></div>'),
		photo_box:Y.template('<div id="photo-box-<%=id%>" class="pure-u-<%=type%> bpp-photo-box bpp-gallery-photo-box">\n    <a href="<%=href%>" target="_blank">\n        <img src="<%=src%>" alt="<%=alt%>" />\n    </a>\n    <aside class="bpp-photo-box-caption">\n        <%=desc%>\n    </aside>\n</div>')
};
}, '@VERSION@',{
    // [bug 5892107] no need to require assets     
    requires:['bpp-template']
});